app:
  name: 'portal'
  version: '1.0.0'

http:
  ip: 127.0.0.1
  port: 8085


logger:
  log_level: 'debug'
  rollbar_env: 'portal'


db:
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  db_name: go_mall_admin
  timeout: 10s

oss:
  base_url: http://macro-oss.oss-cn-shenzhen.aliyuncs.com


jwt:
  time_out: 3600
  issuer: 'baker'
  sign_key: 'baker'
  token_header: 'Authorization'
  token_head: 'Bearer '
  blacklist:
    - '/cart/'
    - '/sso/info'

