// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: portal/coupon.proto

package mall

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 优惠券领取历史详情（包括优惠券信息和关联关系）
type CouponHistoryDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 一、CouponHistory
	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                  // 主键，自增
	MemberId   uint64 `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`      // 会员id
	CouponId   uint64 `protobuf:"varint,3,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`      // 优惠券id
	CouponCode string `protobuf:"bytes,4,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"` // 优惠券码
	OrderId    uint64 `protobuf:"varint,5,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`         // 订单id
	OrderSn    string `protobuf:"bytes,6,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`          // 订单号码
	GetType    uint32 `protobuf:"varint,7,opt,name=get_type,json=getType,proto3" json:"get_type,omitempty"`         // 获取类型：0->后台赠送；1->主动获取
	// 状态
	UseStatus uint32 `protobuf:"varint,8,opt,name=use_status,json=useStatus,proto3" json:"use_status,omitempty"` // 使用状态：0->未使用；1->已使用；2->已过期
	// 时间
	CreateTime uint32 `protobuf:"varint,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间
	UseTime    uint32 `protobuf:"varint,10,opt,name=use_time,json=useTime,proto3" json:"use_time,omitempty"`         // 使用时间
	// 冗余字段
	MemberNickname string `protobuf:"bytes,11,opt,name=member_nickname,json=memberNickname,proto3" json:"member_nickname,omitempty"` // 领取人昵称
	// 二、关联数据
	Coupon            *CouponHistoryDetail_Coupon                          `protobuf:"bytes,100,opt,name=coupon,proto3" json:"coupon,omitempty"`                                                // 相关优惠券信息
	ProductRelations  []*CouponHistoryDetail_CouponProductRelation         `protobuf:"bytes,101,rep,name=product_relations,json=productRelations,proto3" json:"product_relations,omitempty"`    // 优惠券关联商品
	CategoryRelations []*CouponHistoryDetail_CouponProductCategoryRelation `protobuf:"bytes,102,rep,name=category_relations,json=categoryRelations,proto3" json:"category_relations,omitempty"` // 优惠券关联商品分类
}

func (x *CouponHistoryDetail) Reset() {
	*x = CouponHistoryDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_coupon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponHistoryDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponHistoryDetail) ProtoMessage() {}

func (x *CouponHistoryDetail) ProtoReflect() protoreflect.Message {
	mi := &file_portal_coupon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponHistoryDetail.ProtoReflect.Descriptor instead.
func (*CouponHistoryDetail) Descriptor() ([]byte, []int) {
	return file_portal_coupon_proto_rawDescGZIP(), []int{0}
}

func (x *CouponHistoryDetail) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponHistoryDetail) GetMemberId() uint64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *CouponHistoryDetail) GetCouponId() uint64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *CouponHistoryDetail) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *CouponHistoryDetail) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CouponHistoryDetail) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *CouponHistoryDetail) GetGetType() uint32 {
	if x != nil {
		return x.GetType
	}
	return 0
}

func (x *CouponHistoryDetail) GetUseStatus() uint32 {
	if x != nil {
		return x.UseStatus
	}
	return 0
}

func (x *CouponHistoryDetail) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *CouponHistoryDetail) GetUseTime() uint32 {
	if x != nil {
		return x.UseTime
	}
	return 0
}

func (x *CouponHistoryDetail) GetMemberNickname() string {
	if x != nil {
		return x.MemberNickname
	}
	return ""
}

func (x *CouponHistoryDetail) GetCoupon() *CouponHistoryDetail_Coupon {
	if x != nil {
		return x.Coupon
	}
	return nil
}

func (x *CouponHistoryDetail) GetProductRelations() []*CouponHistoryDetail_CouponProductRelation {
	if x != nil {
		return x.ProductRelations
	}
	return nil
}

func (x *CouponHistoryDetail) GetCategoryRelations() []*CouponHistoryDetail_CouponProductCategoryRelation {
	if x != nil {
		return x.CategoryRelations
	}
	return nil
}

// 领取指定优惠券
type CouponAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CouponId uint64 `protobuf:"varint,1,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`
}

func (x *CouponAddReq) Reset() {
	*x = CouponAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_coupon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponAddReq) ProtoMessage() {}

func (x *CouponAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_portal_coupon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponAddReq.ProtoReflect.Descriptor instead.
func (*CouponAddReq) Descriptor() ([]byte, []int) {
	return file_portal_coupon_proto_rawDescGZIP(), []int{1}
}

func (x *CouponAddReq) GetCouponId() uint64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

type CouponAddRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CouponAddRsp) Reset() {
	*x = CouponAddRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_coupon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponAddRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponAddRsp) ProtoMessage() {}

func (x *CouponAddRsp) ProtoReflect() protoreflect.Message {
	mi := &file_portal_coupon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponAddRsp.ProtoReflect.Descriptor instead.
func (*CouponAddRsp) Descriptor() ([]byte, []int) {
	return file_portal_coupon_proto_rawDescGZIP(), []int{2}
}

// 获取会员优惠券历史列表
type CouponListHistoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CouponListHistoryReq) Reset() {
	*x = CouponListHistoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_coupon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponListHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponListHistoryReq) ProtoMessage() {}

func (x *CouponListHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_portal_coupon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponListHistoryReq.ProtoReflect.Descriptor instead.
func (*CouponListHistoryReq) Descriptor() ([]byte, []int) {
	return file_portal_coupon_proto_rawDescGZIP(), []int{3}
}

type CouponListHistoryRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CouponListHistoryRsp) Reset() {
	*x = CouponListHistoryRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_coupon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponListHistoryRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponListHistoryRsp) ProtoMessage() {}

func (x *CouponListHistoryRsp) ProtoReflect() protoreflect.Message {
	mi := &file_portal_coupon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponListHistoryRsp.ProtoReflect.Descriptor instead.
func (*CouponListHistoryRsp) Descriptor() ([]byte, []int) {
	return file_portal_coupon_proto_rawDescGZIP(), []int{4}
}

// 获取会员优惠券列表
type CouponListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CouponListReq) Reset() {
	*x = CouponListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_coupon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponListReq) ProtoMessage() {}

func (x *CouponListReq) ProtoReflect() protoreflect.Message {
	mi := &file_portal_coupon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponListReq.ProtoReflect.Descriptor instead.
func (*CouponListReq) Descriptor() ([]byte, []int) {
	return file_portal_coupon_proto_rawDescGZIP(), []int{5}
}

type CouponListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CouponListRsp) Reset() {
	*x = CouponListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_coupon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponListRsp) ProtoMessage() {}

func (x *CouponListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_portal_coupon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponListRsp.ProtoReflect.Descriptor instead.
func (*CouponListRsp) Descriptor() ([]byte, []int) {
	return file_portal_coupon_proto_rawDescGZIP(), []int{6}
}

// 获取登录会员购物车的相关优惠券
type CouponListCartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *CouponListCartReq) Reset() {
	*x = CouponListCartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_coupon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponListCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponListCartReq) ProtoMessage() {}

func (x *CouponListCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_portal_coupon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponListCartReq.ProtoReflect.Descriptor instead.
func (*CouponListCartReq) Descriptor() ([]byte, []int) {
	return file_portal_coupon_proto_rawDescGZIP(), []int{7}
}

func (x *CouponListCartReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type CouponListCartRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CouponListCartRsp) Reset() {
	*x = CouponListCartRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_coupon_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponListCartRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponListCartRsp) ProtoMessage() {}

func (x *CouponListCartRsp) ProtoReflect() protoreflect.Message {
	mi := &file_portal_coupon_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponListCartRsp.ProtoReflect.Descriptor instead.
func (*CouponListCartRsp) Descriptor() ([]byte, []int) {
	return file_portal_coupon_proto_rawDescGZIP(), []int{8}
}

// 获取当前商品相关优惠券
type CouponListByProductReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId uint64 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (x *CouponListByProductReq) Reset() {
	*x = CouponListByProductReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_coupon_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponListByProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponListByProductReq) ProtoMessage() {}

func (x *CouponListByProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_portal_coupon_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponListByProductReq.ProtoReflect.Descriptor instead.
func (*CouponListByProductReq) Descriptor() ([]byte, []int) {
	return file_portal_coupon_proto_rawDescGZIP(), []int{9}
}

func (x *CouponListByProductReq) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type CouponListByProductRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CouponListByProductRsp) Reset() {
	*x = CouponListByProductRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_coupon_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponListByProductRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponListByProductRsp) ProtoMessage() {}

func (x *CouponListByProductRsp) ProtoReflect() protoreflect.Message {
	mi := &file_portal_coupon_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponListByProductRsp.ProtoReflect.Descriptor instead.
func (*CouponListByProductRsp) Descriptor() ([]byte, []int) {
	return file_portal_coupon_proto_rawDescGZIP(), []int{10}
}

// 相关优惠券信息
type CouponHistoryDetail_Coupon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 基本信息
	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`        //
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`     // 名称
	Amount string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"` // 金额，保留两位小数
	Note   string `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`     // 备注
	Code   string `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`     // 优惠码
	// 类型
	Type    uint32        `protobuf:"varint,10,opt,name=type,proto3" json:"type,omitempty"`                                               // 优惠卷类型；0->全场赠券；1->会员赠券；2->购物赠券；3->注册赠券
	UseType CouponUseType `protobuf:"varint,11,opt,name=use_type,json=useType,proto3,enum=model.CouponUseType" json:"use_type,omitempty"` // 使用类型：0->全场通用；1->指定分类；2->指定商品
	// 使用限制
	EndTime uint32 `protobuf:"varint,18,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"` // 结束使用时间
}

func (x *CouponHistoryDetail_Coupon) Reset() {
	*x = CouponHistoryDetail_Coupon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_coupon_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponHistoryDetail_Coupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponHistoryDetail_Coupon) ProtoMessage() {}

func (x *CouponHistoryDetail_Coupon) ProtoReflect() protoreflect.Message {
	mi := &file_portal_coupon_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponHistoryDetail_Coupon.ProtoReflect.Descriptor instead.
func (*CouponHistoryDetail_Coupon) Descriptor() ([]byte, []int) {
	return file_portal_coupon_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CouponHistoryDetail_Coupon) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponHistoryDetail_Coupon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponHistoryDetail_Coupon) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CouponHistoryDetail_Coupon) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CouponHistoryDetail_Coupon) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CouponHistoryDetail_Coupon) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CouponHistoryDetail_Coupon) GetUseType() CouponUseType {
	if x != nil {
		return x.UseType
	}
	return CouponUseType_COUPON_USE_TYPE_GENERAL
}

func (x *CouponHistoryDetail_Coupon) GetEndTime() uint32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// 优惠券关联商品
type CouponHistoryDetail_CouponProductRelation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CouponId  uint64 `protobuf:"varint,2,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`    // 优惠券id
	ProductId uint64 `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // 商品id
	ProductName string `protobuf:"bytes,4,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"` // 商品名称
	ProductSn   string `protobuf:"bytes,5,opt,name=product_sn,json=productSn,proto3" json:"product_sn,omitempty"`       // 商品条码
}

func (x *CouponHistoryDetail_CouponProductRelation) Reset() {
	*x = CouponHistoryDetail_CouponProductRelation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_coupon_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponHistoryDetail_CouponProductRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponHistoryDetail_CouponProductRelation) ProtoMessage() {}

func (x *CouponHistoryDetail_CouponProductRelation) ProtoReflect() protoreflect.Message {
	mi := &file_portal_coupon_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponHistoryDetail_CouponProductRelation.ProtoReflect.Descriptor instead.
func (*CouponHistoryDetail_CouponProductRelation) Descriptor() ([]byte, []int) {
	return file_portal_coupon_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CouponHistoryDetail_CouponProductRelation) GetCouponId() uint64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *CouponHistoryDetail_CouponProductRelation) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CouponHistoryDetail_CouponProductRelation) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *CouponHistoryDetail_CouponProductRelation) GetProductSn() string {
	if x != nil {
		return x.ProductSn
	}
	return ""
}

// 优惠券关联商品分类
type CouponHistoryDetail_CouponProductCategoryRelation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CouponId          uint64 `protobuf:"varint,2,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`                              // 优惠券id
	ProductCategoryId uint64 `protobuf:"varint,3,opt,name=product_category_id,json=productCategoryId,proto3" json:"product_category_id,omitempty"` // 商品分类id
	ProductCategoryName string `protobuf:"bytes,4,opt,name=product_category_name,json=productCategoryName,proto3" json:"product_category_name,omitempty"` // 商品分类名称
	ParentCategoryName  string `protobuf:"bytes,5,opt,name=parent_category_name,json=parentCategoryName,proto3" json:"parent_category_name,omitempty"`    // 父分类名称
}

func (x *CouponHistoryDetail_CouponProductCategoryRelation) Reset() {
	*x = CouponHistoryDetail_CouponProductCategoryRelation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_coupon_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponHistoryDetail_CouponProductCategoryRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponHistoryDetail_CouponProductCategoryRelation) ProtoMessage() {}

func (x *CouponHistoryDetail_CouponProductCategoryRelation) ProtoReflect() protoreflect.Message {
	mi := &file_portal_coupon_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponHistoryDetail_CouponProductCategoryRelation.ProtoReflect.Descriptor instead.
func (*CouponHistoryDetail_CouponProductCategoryRelation) Descriptor() ([]byte, []int) {
	return file_portal_coupon_proto_rawDescGZIP(), []int{0, 2}
}

func (x *CouponHistoryDetail_CouponProductCategoryRelation) GetCouponId() uint64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *CouponHistoryDetail_CouponProductCategoryRelation) GetProductCategoryId() uint64 {
	if x != nil {
		return x.ProductCategoryId
	}
	return 0
}

func (x *CouponHistoryDetail_CouponProductCategoryRelation) GetProductCategoryName() string {
	if x != nil {
		return x.ProductCategoryName
	}
	return ""
}

func (x *CouponHistoryDetail_CouponProductCategoryRelation) GetParentCategoryName() string {
	if x != nil {
		return x.ParentCategoryName
	}
	return ""
}

var File_portal_coupon_proto protoreflect.FileDescriptor

var file_portal_coupon_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x1a, 0x13, 0x70, 0x6f,
	0x72, 0x74, 0x61, 0x6c, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65,
	0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f,
	0x73, 0x6d, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x94, 0x09, 0x0a, 0x13, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x65, 0x74,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x67, 0x65, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x75, 0x73, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x75, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x27, 0x0a, 0x0f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x63, 0x6f, 0x75, 0x70,
	0x6f, 0x6e, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x06, 0x63, 0x6f, 0x75,
	0x70, 0x6f, 0x6e, 0x12, 0x5d, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x65, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x10, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x67, 0x0a, 0x12, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x66, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x38,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x11, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0xcc, 0x01, 0x0a, 0x06,
	0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2f,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x55,
	0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x75, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x12, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x95, 0x01, 0x0a, 0x15, 0x43,
	0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x53, 0x6e, 0x1a, 0xd2, 0x01, 0x0a, 0x1d, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x2e, 0x0a, 0x13, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49,
	0x64, 0x12, 0x32, 0x0a, 0x15, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x13, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x0c, 0x43, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x70,
	0x6f, 0x6e, 0x49, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x41, 0x64,
	0x64, 0x52, 0x73, 0x70, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x4c, 0x69,
	0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x22, 0x16, 0x0a, 0x14,
	0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x73, 0x70, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x27, 0x0a, 0x11, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22,
	0x13, 0x0a, 0x11, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72,
	0x74, 0x52, 0x73, 0x70, 0x22, 0x37, 0x0a, 0x16, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x4c, 0x69,
	0x73, 0x74, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x22, 0x18, 0x0a,
	0x16, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x52, 0x73, 0x70, 0x32, 0xb5, 0x04, 0x0a, 0x0f, 0x50, 0x6f, 0x72, 0x74,
	0x61, 0x6c, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x41, 0x70, 0x69, 0x12, 0x60, 0x0a, 0x09, 0x43,
	0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x12, 0x13, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x52,
	0x73, 0x70, 0x22, 0x29, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x23, 0x3a, 0x01, 0x2a, 0x22, 0x1e, 0x2f,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2f, 0x61, 0x64,
	0x64, 0x2f, 0x7b, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x71, 0x0a,
	0x11, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x12, 0x1b, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a,
	0x1b, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x4c, 0x69,
	0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x73, 0x70, 0x22, 0x22, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x1c, 0x12, 0x1a, 0x2f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x12, 0x55, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x75,
	0x70, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x15, 0x12, 0x13, 0x2f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x75, 0x70,
	0x6f, 0x6e, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x6d, 0x0a, 0x0e, 0x43, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x74, 0x12, 0x18, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x75, 0x70,
	0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x74, 0x52, 0x73, 0x70, 0x22, 0x27, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x21, 0x12, 0x1f, 0x2f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x63,
	0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x2f,
	0x7b, 0x74, 0x79, 0x70, 0x65, 0x7d, 0x12, 0x86, 0x01, 0x0a, 0x13, 0x43, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1d,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x73, 0x70, 0x22, 0x31, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x2b, 0x12, 0x29, 0x2f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x2f, 0x7b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x7d, 0x42,
	0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x6d, 0x61, 0x6c, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_portal_coupon_proto_rawDescOnce sync.Once
	file_portal_coupon_proto_rawDescData = file_portal_coupon_proto_rawDesc
)

func file_portal_coupon_proto_rawDescGZIP() []byte {
	file_portal_coupon_proto_rawDescOnce.Do(func() {
		file_portal_coupon_proto_rawDescData = protoimpl.X.CompressGZIP(file_portal_coupon_proto_rawDescData)
	})
	return file_portal_coupon_proto_rawDescData
}

var file_portal_coupon_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_portal_coupon_proto_goTypes = []interface{}{
	(*CouponHistoryDetail)(nil),                               // 0: admin.CouponHistoryDetail
	(*CouponAddReq)(nil),                                      // 1: admin.CouponAddReq
	(*CouponAddRsp)(nil),                                      // 2: admin.CouponAddRsp
	(*CouponListHistoryReq)(nil),                              // 3: admin.CouponListHistoryReq
	(*CouponListHistoryRsp)(nil),                              // 4: admin.CouponListHistoryRsp
	(*CouponListReq)(nil),                                     // 5: admin.CouponListReq
	(*CouponListRsp)(nil),                                     // 6: admin.CouponListRsp
	(*CouponListCartReq)(nil),                                 // 7: admin.CouponListCartReq
	(*CouponListCartRsp)(nil),                                 // 8: admin.CouponListCartRsp
	(*CouponListByProductReq)(nil),                            // 9: admin.CouponListByProductReq
	(*CouponListByProductRsp)(nil),                            // 10: admin.CouponListByProductRsp
	(*CouponHistoryDetail_Coupon)(nil),                        // 11: admin.CouponHistoryDetail.Coupon
	(*CouponHistoryDetail_CouponProductRelation)(nil),         // 12: admin.CouponHistoryDetail.CouponProductRelation
	(*CouponHistoryDetail_CouponProductCategoryRelation)(nil), // 13: admin.CouponHistoryDetail.CouponProductCategoryRelation
	(CouponUseType)(0),                                        // 14: model.CouponUseType
}
var file_portal_coupon_proto_depIdxs = []int32{
	11, // 0: admin.CouponHistoryDetail.coupon:type_name -> admin.CouponHistoryDetail.Coupon
	12, // 1: admin.CouponHistoryDetail.product_relations:type_name -> admin.CouponHistoryDetail.CouponProductRelation
	13, // 2: admin.CouponHistoryDetail.category_relations:type_name -> admin.CouponHistoryDetail.CouponProductCategoryRelation
	14, // 3: admin.CouponHistoryDetail.Coupon.use_type:type_name -> model.CouponUseType
	1,  // 4: admin.PortalCouponApi.CouponAdd:input_type -> admin.CouponAddReq
	3,  // 5: admin.PortalCouponApi.CouponListHistory:input_type -> admin.CouponListHistoryReq
	5,  // 6: admin.PortalCouponApi.CouponList:input_type -> admin.CouponListReq
	7,  // 7: admin.PortalCouponApi.CouponListCart:input_type -> admin.CouponListCartReq
	9,  // 8: admin.PortalCouponApi.CouponListByProduct:input_type -> admin.CouponListByProductReq
	2,  // 9: admin.PortalCouponApi.CouponAdd:output_type -> admin.CouponAddRsp
	4,  // 10: admin.PortalCouponApi.CouponListHistory:output_type -> admin.CouponListHistoryRsp
	6,  // 11: admin.PortalCouponApi.CouponList:output_type -> admin.CouponListRsp
	8,  // 12: admin.PortalCouponApi.CouponListCart:output_type -> admin.CouponListCartRsp
	10, // 13: admin.PortalCouponApi.CouponListByProduct:output_type -> admin.CouponListByProductRsp
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_portal_coupon_proto_init() }
func file_portal_coupon_proto_init() {
	if File_portal_coupon_proto != nil {
		return
	}
	file_portal_portal_proto_init()
	file_model_sms_coupon_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_portal_coupon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponHistoryDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_coupon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_coupon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponAddRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_coupon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponListHistoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_coupon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponListHistoryRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_coupon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_coupon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_coupon_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponListCartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_coupon_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponListCartRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_coupon_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponListByProductReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_coupon_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponListByProductRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_coupon_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponHistoryDetail_Coupon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_coupon_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponHistoryDetail_CouponProductRelation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_coupon_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponHistoryDetail_CouponProductCategoryRelation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_portal_coupon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_portal_coupon_proto_goTypes,
		DependencyIndexes: file_portal_coupon_proto_depIdxs,
		MessageInfos:      file_portal_coupon_proto_msgTypes,
	}.Build()
	File_portal_coupon_proto = out.File
	file_portal_coupon_proto_rawDesc = nil
	file_portal_coupon_proto_goTypes = nil
	file_portal_coupon_proto_depIdxs = nil
}
