// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: model/pms_brand.proto

package mall

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Brand 商品品牌
type Brand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                     // 主键
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                  // 名称
	FirstLetter string `protobuf:"bytes,3,opt,name=first_letter,json=firstLetter,proto3" json:"first_letter,omitempty"` // 首字母
	Logo        string `protobuf:"bytes,9,opt,name=logo,proto3" json:"logo,omitempty"`                                  // 品牌logo
	BigPic      string `protobuf:"bytes,10,opt,name=big_pic,json=bigPic,proto3" json:"big_pic,omitempty"`               // 专区大图
	BrandStory  string `protobuf:"bytes,11,opt,name=brand_story,json=brandStory,proto3" json:"brand_story,omitempty"`   // 品牌故事
	Sort        uint32 `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`                                 // 排序
	// status
	FactoryStatus uint32 `protobuf:"varint,5,opt,name=factory_status,json=factoryStatus,proto3" json:"factory_status,omitempty"` // 是否为品牌制造商：0->不是；1->是
	ShowStatus    uint32 `protobuf:"varint,6,opt,name=show_status,json=showStatus,proto3" json:"show_status,omitempty"`          // 是否显示
	// 冗余字段
	ProductCount        uint32 `protobuf:"varint,7,opt,name=product_count,json=productCount,proto3" json:"product_count,omitempty"`                        // 产品数量
	ProductCommentCount uint32 `protobuf:"varint,8,opt,name=product_comment_count,json=productCommentCount,proto3" json:"product_comment_count,omitempty"` // 产品评论数量
}

func (x *Brand) Reset() {
	*x = Brand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_pms_brand_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Brand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Brand) ProtoMessage() {}

func (x *Brand) ProtoReflect() protoreflect.Message {
	mi := &file_model_pms_brand_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Brand.ProtoReflect.Descriptor instead.
func (*Brand) Descriptor() ([]byte, []int) {
	return file_model_pms_brand_proto_rawDescGZIP(), []int{0}
}

func (x *Brand) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Brand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Brand) GetFirstLetter() string {
	if x != nil {
		return x.FirstLetter
	}
	return ""
}

func (x *Brand) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *Brand) GetBigPic() string {
	if x != nil {
		return x.BigPic
	}
	return ""
}

func (x *Brand) GetBrandStory() string {
	if x != nil {
		return x.BrandStory
	}
	return ""
}

func (x *Brand) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *Brand) GetFactoryStatus() uint32 {
	if x != nil {
		return x.FactoryStatus
	}
	return 0
}

func (x *Brand) GetShowStatus() uint32 {
	if x != nil {
		return x.ShowStatus
	}
	return 0
}

func (x *Brand) GetProductCount() uint32 {
	if x != nil {
		return x.ProductCount
	}
	return 0
}

func (x *Brand) GetProductCommentCount() uint32 {
	if x != nil {
		return x.ProductCommentCount
	}
	return 0
}

var File_model_pms_brand_proto protoreflect.FileDescriptor

var file_model_pms_brand_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x70, 0x6d, 0x73, 0x5f, 0x62, 0x72, 0x61, 0x6e,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0xd1,
	0x02, 0x0a, 0x05, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c,
	0x6f, 0x67, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x69, 0x67, 0x5f, 0x70, 0x69, 0x63, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x69, 0x67, 0x50, 0x69, 0x63, 0x12, 0x1f, 0x0a, 0x0b,
	0x62, 0x72, 0x61, 0x6e, 0x64, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6f, 0x72,
	0x74, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x66, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x77,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73,
	0x68, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x32,
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x13, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x6d, 0x61, 0x6c, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_pms_brand_proto_rawDescOnce sync.Once
	file_model_pms_brand_proto_rawDescData = file_model_pms_brand_proto_rawDesc
)

func file_model_pms_brand_proto_rawDescGZIP() []byte {
	file_model_pms_brand_proto_rawDescOnce.Do(func() {
		file_model_pms_brand_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_pms_brand_proto_rawDescData)
	})
	return file_model_pms_brand_proto_rawDescData
}

var file_model_pms_brand_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_pms_brand_proto_goTypes = []interface{}{
	(*Brand)(nil), // 0: model.Brand
}
var file_model_pms_brand_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_pms_brand_proto_init() }
func file_model_pms_brand_proto_init() {
	if File_model_pms_brand_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_pms_brand_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Brand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_pms_brand_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_pms_brand_proto_goTypes,
		DependencyIndexes: file_model_pms_brand_proto_depIdxs,
		MessageInfos:      file_model_pms_brand_proto_msgTypes,
	}.Build()
	File_model_pms_brand_proto = out.File
	file_model_pms_brand_proto_rawDesc = nil
	file_model_pms_brand_proto_goTypes = nil
	file_model_pms_brand_proto_depIdxs = nil
}
