// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: model/pms_product_category_attribute_relation.proto

package mall

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ProductCategoryAttributeRelation with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ProductCategoryAttributeRelation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProductCategoryAttributeRelation with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ProductCategoryAttributeRelationMultiError, or nil if none found.
func (m *ProductCategoryAttributeRelation) ValidateAll() error {
	return m.validate(true)
}

func (m *ProductCategoryAttributeRelation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ProductCategoryId

	// no validation rules for ProductAttributeId

	if len(errors) > 0 {
		return ProductCategoryAttributeRelationMultiError(errors)
	}

	return nil
}

// ProductCategoryAttributeRelationMultiError is an error wrapping multiple
// validation errors returned by
// ProductCategoryAttributeRelation.ValidateAll() if the designated
// constraints aren't met.
type ProductCategoryAttributeRelationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProductCategoryAttributeRelationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProductCategoryAttributeRelationMultiError) AllErrors() []error { return m }

// ProductCategoryAttributeRelationValidationError is the validation error
// returned by ProductCategoryAttributeRelation.Validate if the designated
// constraints aren't met.
type ProductCategoryAttributeRelationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProductCategoryAttributeRelationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProductCategoryAttributeRelationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProductCategoryAttributeRelationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProductCategoryAttributeRelationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProductCategoryAttributeRelationValidationError) ErrorName() string {
	return "ProductCategoryAttributeRelationValidationError"
}

// Error satisfies the builtin error interface
func (e ProductCategoryAttributeRelationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProductCategoryAttributeRelation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProductCategoryAttributeRelationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProductCategoryAttributeRelationValidationError{}
