// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: model/pms_product_attribute.proto

package mall

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 商品属性
type ProductAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // 编号
	Type                       uint32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`                                                                                   // 属性的类型；0->规格；1->参数
	ProductAttributeCategoryId uint64 `protobuf:"varint,3,opt,name=product_attribute_category_id,json=productAttributeCategoryId,proto3" json:"product_attribute_category_id,omitempty"` // 产品属性分类表ID
	Name                       string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                                                                    // 属性名称
	Sort                       uint32 `protobuf:"varint,8,opt,name=sort,proto3" json:"sort,omitempty"`                                                                                   // 排序字段
	SelectType uint32 `protobuf:"varint,5,opt,name=select_type,json=selectType,proto3" json:"select_type,omitempty"` // 属性选择类型：0->唯一；1->单选；2->多选
	InputType  uint32 `protobuf:"varint,6,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`    // 属性录入方式：0->手工录入；1->从列表中选取
	InputList  string `protobuf:"bytes,7,opt,name=input_list,json=inputList,proto3" json:"input_list,omitempty"`     // 可选值列表，以逗号隔开
	FilterType uint32 `protobuf:"varint,9,opt,name=filter_type,json=filterType,proto3" json:"filter_type,omitempty"`  // 分类筛选样式：1->普通；1->颜色
	SearchType uint32 `protobuf:"varint,10,opt,name=search_type,json=searchType,proto3" json:"search_type,omitempty"` // 检索类型；0->不需要进行检索；1->关键字检索；2->范围检索
	RelatedStatus uint32 `protobuf:"varint,11,opt,name=related_status,json=relatedStatus,proto3" json:"related_status,omitempty"`   // 相同属性产品是否关联；0->不关联；1->关联
	HandAddStatus uint32 `protobuf:"varint,12,opt,name=hand_add_status,json=handAddStatus,proto3" json:"hand_add_status,omitempty"` // 是否支持手动新增；0->不支持；1->支持
}

func (x *ProductAttribute) Reset() {
	*x = ProductAttribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_pms_product_attribute_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttribute) ProtoMessage() {}

func (x *ProductAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_model_pms_product_attribute_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttribute.ProtoReflect.Descriptor instead.
func (*ProductAttribute) Descriptor() ([]byte, []int) {
	return file_model_pms_product_attribute_proto_rawDescGZIP(), []int{0}
}

func (x *ProductAttribute) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductAttribute) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ProductAttribute) GetProductAttributeCategoryId() uint64 {
	if x != nil {
		return x.ProductAttributeCategoryId
	}
	return 0
}

func (x *ProductAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductAttribute) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ProductAttribute) GetSelectType() uint32 {
	if x != nil {
		return x.SelectType
	}
	return 0
}

func (x *ProductAttribute) GetInputType() uint32 {
	if x != nil {
		return x.InputType
	}
	return 0
}

func (x *ProductAttribute) GetInputList() string {
	if x != nil {
		return x.InputList
	}
	return ""
}

func (x *ProductAttribute) GetFilterType() uint32 {
	if x != nil {
		return x.FilterType
	}
	return 0
}

func (x *ProductAttribute) GetSearchType() uint32 {
	if x != nil {
		return x.SearchType
	}
	return 0
}

func (x *ProductAttribute) GetRelatedStatus() uint32 {
	if x != nil {
		return x.RelatedStatus
	}
	return 0
}

func (x *ProductAttribute) GetHandAddStatus() uint32 {
	if x != nil {
		return x.HandAddStatus
	}
	return 0
}

var File_model_pms_product_attribute_proto protoreflect.FileDescriptor

var file_model_pms_product_attribute_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x70, 0x6d, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x91, 0x03, 0x0a, 0x10, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x41, 0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x1a, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f,
	0x72, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x25, 0x0a, 0x0e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x68, 0x61, 0x6e, 0x64, 0x5f, 0x61,
	0x64, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0d, 0x68, 0x61, 0x6e, 0x64, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x08,
	0x5a, 0x06, 0x2e, 0x3b, 0x6d, 0x61, 0x6c, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_pms_product_attribute_proto_rawDescOnce sync.Once
	file_model_pms_product_attribute_proto_rawDescData = file_model_pms_product_attribute_proto_rawDesc
)

func file_model_pms_product_attribute_proto_rawDescGZIP() []byte {
	file_model_pms_product_attribute_proto_rawDescOnce.Do(func() {
		file_model_pms_product_attribute_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_pms_product_attribute_proto_rawDescData)
	})
	return file_model_pms_product_attribute_proto_rawDescData
}

var file_model_pms_product_attribute_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_pms_product_attribute_proto_goTypes = []interface{}{
	(*ProductAttribute)(nil), // 0: model.ProductAttribute
}
var file_model_pms_product_attribute_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_pms_product_attribute_proto_init() }
func file_model_pms_product_attribute_proto_init() {
	if File_model_pms_product_attribute_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_pms_product_attribute_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductAttribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_pms_product_attribute_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_pms_product_attribute_proto_goTypes,
		DependencyIndexes: file_model_pms_product_attribute_proto_depIdxs,
		MessageInfos:      file_model_pms_product_attribute_proto_msgTypes,
	}.Build()
	File_model_pms_product_attribute_proto = out.File
	file_model_pms_product_attribute_proto_rawDesc = nil
	file_model_pms_product_attribute_proto_goTypes = nil
	file_model_pms_product_attribute_proto_depIdxs = nil
}
